spring.datasource.url=jdbc:sqlite:${LS_SQLITE_PATH:../../.self-host/lobby.sqlite}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.sqlite.hibernate.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=
spring.datasource.password=
hibernate.hbm2ddl.auto=update
